name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  COVERAGE: '0'

jobs:
  test:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        go:
          - '1.13'
          - '1.14'
          - '1.15'
        include:
          - go: 1.15
            coverage: true
    name: Test (go-${{ matrix.go }})
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: Enable code coverage
        if: matrix.coverage
        run: echo '::set-env name=COVERAGE::1'
      - run: |
          if [ "$COVERAGE" == '1' ]; then
            go test `go list ./... | grep -v examples` -coverprofile=coverage.txt -covermode=atomic
          else
            go test ./...
          fi
      - name: Upload coverage report
        if: matrix.coverage
        uses: codecov/codecov-action@v1
        with:
          name: test-go${{ matrix.go }}
          file: ./coverage.txt
          flags: unittests
